---
title: "useR: Spatial optimisation with OSRM and R"
output: html_notebook
---

```{r include=FALSE}
# LIBRARIES
library(osrm)
library(leaflet)
library(tidyverse)

# OSRM SERVER
 options(osrm.server = "http://127.0.0.1:5000/")
```

```{r}
# LOCATION
loc <- c(1.428678, 43.598139)

```

```{r}
iso <- osrmIsochrone(loc, breaks = seq(from = 0, to = 30, by = 5), res = 400)
```

```{r}
# PLOT WITH LEAFLET
# Create factor for colour scale
iso@data$run_times <- factor(paste(iso@data$min, "to", iso@data$max, "min"),
                              levels = c("0 to 5 min", "5 to 10 min", "10 to 15 min", "15 to 20 min", "20 to 25 min", "25 to 30 min"))

# Colour palette for each area
factpal <- colorFactor(rev(heat.colors(6)), iso@data$run_times)

leaflet(data = iso) %>% 
  setView(lng = 1.428678, lat = 43.598139, zoom = 13) %>%
  addTiles() %>% 
  addMarkers(lng = 1.428678, lat = 43.598139, popup = "My Airbnb") %>%
  addPolygons(fill=TRUE, stroke=TRUE, color = "black",
                                        fillColor = ~factpal(iso@data$run_times),
                                        weight=0.5, fillOpacity=0.3,
                                        data = iso, popup = iso@data$run_times,
                                        group = "Running Time") %>% 
                # Legend
                addLegend("bottomright", pal = factpal, values = iso@data$run_times,   title = "Running Time")

  
```

